# Generated by Django 5.2.8 on 2025-12-14 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Когда пользователь подписался на курс",
                        verbose_name="Дата подписки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Активна ли подписка (можно отключать без удаления)",
                        verbose_name="Активность подписки",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Курс, на обновления которого подписался пользователь",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, подписанный на обновления курса",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка на курс",
                "verbose_name_plural": "Подписки на курсы",
                "unique_together": {("user", "course")},
            },
        ),
    ]
