# Generated by Django 5.2.8 on 2025-12-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_payment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(
                help_text="Сумма платежа в рублях", verbose_name="Сумма оплаты"
            ),
        ),
    ]
