# Generated by Django 5.2.8 on 2025-12-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на оплату",
                max_length=500,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
