# Generated by Django 5.2.8 on 2025-12-23 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_course_updated_at"),
        ("users", "0006_alter_payment_payment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                help_text="Курс, на обновления которого подписался пользователь",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь, подписанный на обновления курса",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
