# Generated by Django 5.2.8 on 2025-12-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего изменения курса (включая связанные уроки)",
                verbose_name="Дата последнего обновления",
            ),
        ),
    ]
